---
name: Verify

on:
  pull_request:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  homeassistant:
    runs-on: ubuntu-latest
    name: Verify Home Assistant Configuration
    strategy:
      max-parallel: 4
      matrix:
        home-assistant-version:
          - stable
          - beta
          - dev

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Prepare data
        run: |
          ./lifecycle/prepare.sh configuration

      - name: Check Home Assistant Configuration
        uses: frenck/action-home-assistant@941d5d917f4c1c7a7e7d4087526daf90d53f4437 # v1.4.1
        with:
          path: configuration
          secrets: .ci/secrets.yaml
          env_file: .ci/env
          version: "${{ matrix.home-assistant-version }}"
